BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');


INSERT INTO quotes (quote_text,quote_author) VALUES ('Success isn''t always about greatness. It''s about consistency. Consistent hard work leads to success. Greatness will come.', 'Dwayne Johnson');
INSERT INTO quotes (quote_text,quote_author) VALUES ('Luck? I don''t know anything about luck. Luck to me is something else: hard work and realizing what is opportunity and what isn''t.', 'Lucille Ball');
INSERT INTO quotes (quote_text,quote_author) VALUES ('Ambition is the path to success. Persistence is the vehicle you arrive in.','Bill Bradley');
INSERT INTO quotes (quote_text,quote_author) VALUES ('You keep putting one foot in front of the other, and one day you look back and you''ve climbed a mountain.', 'Tom Hiddleston');
INSERT INTO quotes (quote_text,quote_author) VALUES ('Keep a little fire burning, however small, however hidden.', 'Cormac McCarthy');
INSERT INTO quotes (quote_text,quote_author) VALUES ('We are what we repeatedly do. Excellence, then, is not an act but a habit.', 'Aristotle');
INSERT INTO quotes (quote_text,quote_author) VALUES ('Hang onto your hat, hang onto your hope and wind the clock, for tomorrow is another day.', 'E.B. White');
INSERT INTO quotes (quote_text,quote_author) VALUES ('The gem cannot be polished without friction, nor man perfected without trials.','Chinese proverb');
INSERT INTO quotes (quote_text,quote_author) VALUES ('You cannot change your destination overnight, but you can change your direction overnight.', 'Jim Rohn');
INSERT INTO quotes (quote_text,quote_author) VALUES('If everybody is doing it one way, there''s a good chance you can find your niche by going exactly in the opposite direction.', 'Sam Walton');
INSERT INTO quotes (quote_text,quote_author) VALUES ('You''ve got to think about the big things while you''re doing the small things so that all the small things go in the right direction.', 'Alvin Toffler');
INSERT INTO quotes (quote_text,quote_author) VALUES ( 'Success is often the result of taking a misstep in the right direction.','Al Bernstein');
INSERT INTO quotes (quote_text,quote_author) VALUES('If you hear a voice within you say, ''You cannot paint,'' then by all means paint, and that voice will be silenced.','Vincent van Gogh');
INSERT INTO quotes (quote_text,quote_author) VALUES ('To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.','Ralph Waldo Emerson');
INSERT INTO quotes (quote_text,quote_author) VALUES ('If opportunity doesn''t knock, build a door.','Milton Berle');
INSERT INTO quotes (quote_text,quote_author) VALUES ('Striving for success without hard work is like trying to harvest where you haven’t planted.','David Bly');
INSERT INTO quotes (quote_text,quote_author) VALUES ('Sometimes when you''re in a dark place you think you''ve been buried, but you''ve actually been planted.','Christine Caine');
INSERT INTO quotes (quote_text,quote_author) VALUES ('A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.', 'Winston S. Churchill');
INSERT INTO quotes (quote_text,quote_author) VALUES ('Courage starts with showing up and letting ourselves be seen.', 'Brene Brown');
INSERT INTO quotes (quote_text,quote_author) VALUES ('The voyage of discovery is not in looking for new landscapes, but in looking with new eyes.','Anonymous');
INSERT INTO quotes (quote_text,quote_author) VALUES ('Only those who dare to fail greatly can ever achieve greatly.', 'Robert F. Kennedy');
INSERT INTO quotes (quote_text,quote_author) VALUES ('All of the darkness of the world cannot put out the light of one small candle.','Anonymous');
INSERT INTO quotes (quote_text,quote_author) VALUES ('If one advances confidently in the direction of his dreams,and endeavors to live the life which he has imagined,he will meet with a success unexpected in common hours.','Henry David Thoreau');
INSERT INTO quotes (quote_text,quote_author) VALUES ('Excellence is to do a common thing in an uncommon way.','Booker T. Washington');
INSERT INTO quotes (quote_text,quote_author) VALUES ('Don’t be afraid to go out on a limb. That’s where the fruit is.', 'H. Jackson Browne');
INSERT INTO quotes (quote_text,quote_author) VALUES ('Don''t be afraid to fail. Don''t waste energy trying to cover up failure. Learn from your failures and go on to the next challenge. It''s OK to fail. If you''re not failing, you''re not growing.','H. Stanley Judd');
INSERT INTO quotes (quote_text,quote_author) VALUES ('Opportunities don''t often come along. So, when they do, you have to grab them.','Audrey Hepburn');
INSERT INTO quotes (quote_text,quote_author) VALUES ('When one door closes, another opens; but we often look so long and so regretfully upon the closed door that we do not see the one which has opened for us.', 'Alexander Graham Bell');
INSERT INTO quotes (quote_text,quote_author) VALUES ('Never tell me the sky’s the limit when there are footprints on the moon.','Author Unknown');
INSERT INTO quotes (quote_text,quote_author) VALUES ('Every experience in your life is being orchestrated to teach you something you need to know to move forward.', 'Brian Tracy');

INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('First message','I can help you with pathway information or get you a motivational quote, which would you like,','default','default','default');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('First pathway message','I can help you with your Resume, a Cover Letter, or Interview Prep. What would you like to talk about?','pathway','default','default');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('pathway/resume main','I can break down the main components of a resume or provide you with links to examples of resumes. Which would you like?','pathway','resume','default');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('pathway/interview main','I can help you with Interview Prep, following up with employers, what to wear to interviews, or common STAR questions. Which would you like help with?','pathway','interview','default');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('pathway/interview prep','"Here are some tips to help you prepare for an interview! - Familiarize yourself with the company and representative you will be interviewing with. - Practice common questions for the field prior to the interview. - Ensure you get a good night''s sleep the night before.','pathway','interview','prep');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('pathway/follow up','Here are some tips for following up with an employer after an interview: Send a thank you note to all parties present at the interview within 24 hours.','pathway','interview','follow');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('pathway/cover main','I can show you the components of a cover letter or examples of a cover letter. Which would you like?','pathway','cover','default');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('pathway/cover parts','"The main parts of a cover letter are as follows: Personal Information, Receiving Party Info, Salutation, Letter Body and Closing','pathway','cover','parts');

INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('pathway/resume parts','<ul><li>Here are the main parts of a technical resume: Name & Contact Information, Professional Summary, Technical Skills, Technical Experience, Education, and Professional Experience. If you would like a template you can find one at this link!</li> <li><a href="https://careerservices.fas.harvard.edu/resources/bullet-point-resume-template">Resume Template</a></li>,'pathway', 'resume','parts');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('pathway/resume links','Here are a few example resumes!','https://edu.gcfglobal.org/en/resumewriting/gallery-of-sample-resumes/1/#','pathway','resume','links');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('pathway/interview outfit','Here are some links to help you understand what is appropriate dress for an interview!','https://www.coursera.org/articles/what-to-wear-to-an-interview','pathway','interview','outfit');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('pathway/interview star','Here is a list of common STAR questions. This page also includes a form to help you brainstorm and keep track of your responses!','https://docs.google.com/spreadsheets/d/1bDueF61fW5FNTbJNIhkmmA2U5LqIpI1j1IoEmtrxfJc/copy','pathway','interview','star');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('pathway/cover examples','Here are a few example cover letters!','https://novoresume.com/career-blog/cover-letter-examples','pathway','cover','links');

INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('First Curriculum Message', 'In regards to curriculum, I can help you with these topics: Java programming, Client-Server Programming, Web Application Development, and Databases. Which of these would you like to explore?', 'curriculum', 'default', 'default');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/java', 'For Java, I can help you with variables, arrays, collections, unit testing, Object-Oriented Programming (OOP)', 'curriculum', 'java', 'default');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/java/variables', 'If you need help with variables and data types, please refer to the BootcampOS section in Intro to Programming in Java titled Variables and data types', 'curriculum', 'java', 'variables');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/java/collections', 'To understand collections better you can view the BootcampOS section Intro to Programming in Java titled Collections - Part 1 & 2', 'curriculum', 'java', 'collections');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/clientserver', 'For Client-Server, I can help you with Server-side APIs, DAOs, Networking. Which of these would you like to know more about?', 'curriculum', 'clientserver', 'default');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/clientserver/dao', 'If you want more information on DAOs, you can look to the Data Access and DAO section within the Client-Server Programming in Java module', 'curriculum', 'clientserver', 'dao');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/webapp', 'For Web Application Development, I can help you with CSS, HTML, Javascript, and Vue. Please let me know which of these topics you would like to know more about.', 'curriculum', 'webapp', 'default');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/webapp/javascript', 'It might be a good idea to check the BootcampOS module Web Application Development where you can find the section called Intro to Javascript.', 'curriculum', 'webapp', 'javascript');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/clientserver/dao', 'If you want more information on DAOs, you can look to the Data Access and DAO section within the Client-Server Programming in Java module', 'curriculum', 'clientserver', 'dao');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/databases', 'For Databases, I can help you with  SQL, Database Design, or Data Security. Which of these topics would you like help with?', 'curriculum', 'databases', 'default');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/databases/sql', 'In the BootcampOS module, Client-Server Programming in Java, there are a handful of modules that can help with SQL. I would start with the Intro to Databases section, then you can look at: Ordering, Limiting, and Grouping or SQL joins or Insert, Update and Delete depending on what you need help with', 'curriculum', 'databases', 'sql');

INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/java/arrays','For more information on arrays outside of the reading and lecture, you can view this page:', 'https://www.javatpoint.com/array-in-java','curriculum', 'java','arrays');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/java/unittesting','This page helps break down how to set up unit testing in Java:', 'https://www.baeldung.com/java-unit-testing-best-practices','curriculum', 'java','unittesting');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/java/oop','This video is a great explanation on how Object-Oriented Programming works:', 'https://www.youtube.com/watch?v=pTB0EiLXUC8a','curriculum', 'java','oop');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/clientserver/api','In order to help understand how APIs work, this video will expain Restful APIs:', 'https://www.youtube.com/watch?v=lsMQRaeKNDk','curriculum', 'clientserver','api');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/clientserver/networking','This Mozilla page on HTTP is a useful site with lots of additional resources to help you understand networking in the client-server model', 'https://developer.mozilla.org/en-US/docs/Web/HTTP','curriculum', 'clientserver','networking');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/webapp/css','Mozilla has a very nice page on how to start out with CSS that expands to many specific topics. I hope this link helps: ', 'https://developer.mozilla.org/en-US/docs/Learn/CSS','curriculum', 'webapp','css');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/webapp/htmls','This video gives a good basic overview of what HTML if you would like to go beyond the reading and lecture:', 'https://www.youtube.com/watch?v=salY_Sm6mv4','curriculum', 'webapp','html');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/webapp/vue','The Vue.js website is a very helpful resource for all things related to Vue.js. I recommend bookmarking this link: ', 'https://vuejs.org/guide/introduction.html','curriculum', 'webapp','vue');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/databases/databasedesign','Not only is Lucidchart is a great tool to play around with for helping visualize databases but this page is also a great in depth resource on Database Structure and Design', 'https://www.lucidchart.com/pages/database-diagram/database-design','curriculum', 'databases','databasedesign');
INSERT INTO response (response_description, response_text, need_category, keyword_1, keyword_2) VALUES ('curriculum/databases/datasecurity','For more information beyond the lecture and reading this link gives you a more in depth explanation of some of the topics you have or will cover: ', 'https://satoricyber.com/sql-server-security/sql-server-security/','curriculum', 'databases','datasecurity');



COMMIT TRANSACTION;
